flyway-gradle-plugin-largetest/src/test/java/org/flywaydb/gradle/largetest/GradleLargeTest.java
flyway-gradle-plugin-largetest/src/test/resources/tests/error/build.gradle
flyway-gradle-plugin-largetest/src/test/resources/tests/unqualified/build.gradle
flyway-gradle-plugin-largetest/src/test/resources/tests/unqualified/src/main/resources/db/migration/V1_1__Populate_table.sql
flyway-gradle-plugin-largetest/src/test/resources/tests/unqualified/src/main/resources/db/migration/V1__First.sql
flyway-gradle-plugin/src/main/groovy/org/flywaydb/gradle/UnqualifiedFlywayPlugin.java
flyway-gradle-plugin/src/main/resources/META-INF/gradle-plugins/org.flywaydb.flyway.properties
flyway-gradle-plugin/src/test/groovy/org/flywaydb/gradle/UnqualifiedFlywayPluginSmallTest.groovy
flyway-sample/build.gradle

This change is backwards-compatible.  The existing "flyway" unqualified plugin ID is fully functional, albeit now with a logged warning message that it is deprecated.  The new "org.flywaydb.flyway" qualified plugin ID has all the same capabilities, minus the warning.
To verify that this is actually the case, all the test coverage is duplicated, covering both the qualified and unqualified plugin IDs.  In the case of `GradleLargeTest`, the `unqualified` test checks that there is a deprecation message in the output.
In the next major version, it should be possible to remove `UnqualifiedFlywayPlugin.java`, `flyway.properties`, and the associated test coverage.

#895: Add qualified Gradle plugin ID, deprecate unqualified Gradle plugin ID

---

flyway-core/src/main/java/org/flywaydb/core/internal/metadatatable/MetaDataTableImpl.java

Syntax error encountered on MySQL due to missing space after "OR" in SQL query in MetaDataTableImpl.java.

Fix SQL syntax error in MetaDataTableImpl.java

---

flyway-commandline/pom.xml
flyway-commandline/src/main/java/org/flywaydb/commandline/ConsoleLog.java
flyway-commandline/src/test/java/org/flywaydb/commandline/ConsoleLogTest.java

I need to redirect error messages from command line into separate file. It's possible to use ```|grep 'ERROR:'``` but it will not catch exception stacktraces, because they are not prefixed with ```ERROR:```
I think this is a good behavior for command line tool

Print error messages to stderr(System.err) from CLI

---

flyway-core/src/main/java/org/flywaydb/core/internal/dbsupport/JdbcTemplate.java

Our DBA team want to be able to see the number of rows updated by Flyway.  We occasionally have data migrations via an UPDATE statement, and we want to record the number of rows updated in each database environment for auditing purposes.  I've logged with DEBUG priority because most users obviously don't need this feature.

Log the update count with DEBUG priority after running a SQL script

---

flyway-core/src/main/java/org/flywaydb/core/internal/dbsupport/DbSupportFactory.java
flyway-core/src/main/java/org/flywaydb/core/internal/dbsupport/redshift/RedshfitDbSupportViaPostgreSQLDriver.java
flyway-core/src/main/java/org/flywaydb/core/internal/dbsupport/redshift/RedshfitDbSupportViaRedshiftDriver.java
flyway-core/src/main/java/org/flywaydb/core/internal/dbsupport/redshift/RedshiftDbSupport.java
flyway-core/src/main/java/org/flywaydb/core/internal/dbsupport/redshift/RedshiftSchema.java
flyway-core/src/main/java/org/flywaydb/core/internal/dbsupport/redshift/RedshiftTable.java
flyway-core/src/main/java/org/flywaydb/core/internal/util/jdbc/DriverDataSource.java
flyway-core/src/test/java/org/flywaydb/core/internal/dbsupport/redshift/RedshiftDbSupportMediumTest.java
flyway-core/src/test/java/org/flywaydb/core/internal/dbsupport/redshift/RedshiftDbSupportSmallTest.java
flyway-core/src/test/java/org/flywaydb/core/internal/dbsupport/redshift/RedshiftMigrationMediumTest.java
flyway-core/src/test/resources/migration/dbsupport/redshift/sql/dollar/V1__Dollar.sql

Proposed implementation #1058, using detectDriverForUrl for the JDBC 4.1 driver and detectBackupDriverForUrl for JDBC 4 driver. I also had to fix a couple of bugs along the way to make the tests pass.

Add support for the Redshift-specific JDBC driver

---

flyway-commandline/src/main/assembly/flyway

New Git Bash for Windows (https://git-for-windows.github.io/) is recognized
as "MINGW..." system. For example on my test machine `uname` returns
the following:
```
$ uname
MINGW64_NT-6.1
```
This patch expands on the fix done in #735 to use Windows classpath
separator when running in Git Bash for Windows.

Fix flyway script on Git Bash for Windows

---

flyway-core/src/main/java/org/flywaydb/core/internal/util/StopWatch.java

Measuring durations with currentTimeMillis() can produce incorrect
results, even negative values, if the system clock is adjusted.

Use nanoTime() for StopWatch

---

flyway-core/src/main/java/org/flywaydb/core/internal/util/scanner/classpath/OsgiClassPathLocationScanner.java

enhancement for  #1142.
Makes OsgiClassPathLocationScanner try to get target bundle from url first instead of the current one if possible. If it's not possible it still keeps fallback to current bundle

Modification of OsgiClassPathLocationScanner to support not only current bundle

---

flyway-core/src/main/java/org/flywaydb/core/internal/util/jdbc/DriverDataSource.java

Fixes #1171 
See https://cloud.google.com/appengine/docs/java/cloud-sql/

#1171: Fix "jdbc:google:" for new GAE versions.

---

.gitignore

a clean checkout and build resulted in a .h2.db file that wasn't ignored.

added temporary db files to ignore

---

flyway-core/src/main/java/org/flywaydb/core/Flyway.java
flyway-core/src/main/java/org/flywaydb/core/api/ConfigurationAware.java
flyway-core/src/main/java/org/flywaydb/core/api/FlywayConfiguration.java
flyway-core/src/main/java/org/flywaydb/core/api/callback/FlywayCallback.java
flyway-core/src/main/java/org/flywaydb/core/api/migration/jdbc/JdbcMigration.java
flyway-core/src/main/java/org/flywaydb/core/internal/resolver/CompositeMigrationResolver.java
flyway-core/src/main/java/org/flywaydb/core/internal/resolver/jdbc/JdbcMigrationResolver.java
flyway-core/src/main/java/org/flywaydb/core/internal/resolver/spring/SpringJdbcMigrationResolver.java
flyway-core/src/main/java/org/flywaydb/core/internal/resolver/sql/SqlMigrationResolver.java
flyway-core/src/main/java/org/flywaydb/core/internal/util/ClassUtils.java
flyway-core/src/main/java/org/flywaydb/core/internal/util/InjectionUtils.java
flyway-core/src/test/java/org/flywaydb/core/FlywayCallbackImpl.java
flyway-core/src/test/java/org/flywaydb/core/FlywayCallbackSmallTest.java
flyway-core/src/test/java/org/flywaydb/core/FlywayResolverImpl.java
flyway-core/src/test/java/org/flywaydb/core/FlywaySmallTest.java
flyway-core/src/test/java/org/flywaydb/core/internal/resolver/CompositeMigrationResolverSmallTest.java
flyway-core/src/test/java/org/flywaydb/core/internal/resolver/FlywayConfigurationForTests.java
flyway-core/src/test/java/org/flywaydb/core/internal/resolver/MyConfigurationAwareCustomMigrationResolver.java
flyway-core/src/test/java/org/flywaydb/core/internal/resolver/jdbc/JdbcMigrationResolverSmallTest.java
flyway-core/src/test/java/org/flywaydb/core/internal/resolver/spring/SpringJdbcMigrationResolverSmallTest.java
flyway-core/src/test/java/org/flywaydb/core/internal/resolver/sql/SqlMigrationResolverMediumTest.java
flyway-core/src/test/java/org/flywaydb/core/internal/resolver/sql/SqlMigrationResolverSmallTest.java
flyway-core/src/test/java/org/flywaydb/core/migration/MigrationTestCase.java

Introduced a generic ConfigurationAware interface.
If a custom resolver or callback implements `ConfigurationAware`, the `FlywayConfiguration` get automatically injected. That way, resolvers and callbacks have access to important configurations like the locations (for custom resolvers) or PlaceholderResolvers.
Right now, Flyway implements FlywayConfiguration directly.

Implementation for #805: JdbcMigrations, Resolvers and FlywayCallbacks should have access to core configuration

---

flyway-ant/src/main/java/org/flywaydb/ant/AbstractFlywayTask.java
flyway-commandline/src/main/assembly/flyway.conf
flyway-commandline/src/main/java/org/flywaydb/commandline/Main.java
flyway-core/src/main/java/org/flywaydb/core/Flyway.java
flyway-core/src/main/java/org/flywaydb/core/api/configuration/FlywayConfiguration.java
flyway-core/src/main/java/org/flywaydb/core/internal/resolver/CompositeMigrationResolver.java
flyway-core/src/test/java/org/flywaydb/core/internal/resolver/CompositeMigrationResolverSmallTest.java
flyway-core/src/test/java/org/flywaydb/core/internal/resolver/FlywayConfigurationForTests.java
flyway-gradle-plugin/src/main/groovy/org/flywaydb/gradle/FlywayExtension.groovy
flyway-gradle-plugin/src/main/groovy/org/flywaydb/gradle/task/AbstractFlywayTask.groovy
flyway-maven-plugin/src/main/java/org/flywaydb/maven/AbstractFlywayMojo.java
flyway-sbt/src/main/scala/org/flywaydb/sbt/FlywayPlugin.scala

This allows to completely skip the usage of the built-in resolvers and thus only rely on custom resolvers.

Introduce skipDefaultResolvers property

---

flyway-core/src/main/java/org/flywaydb/core/internal/dbsupport/postgresql/PostgreSQLSchema.java
flyway-core/src/test/resources/migration/dbsupport/postgresql/sql/materializedview/V1__MaterializedView.sql
flyway-core/src/test/resources/migration/dbsupport/postgresql/sql/procedure/V1__Procedure.sql
flyway-core/src/test/resources/migration/dbsupport/postgresql/sql/type/V1__Type.sql

This is the follow-up of #1157.
All tests are now running.
I failed to merge/rebase my fork against upstream, I hope it won't cause any issue.

PostgreSQL: Filter functions and views from extensions during clean

---

flyway-core/src/main/java/org/flywaydb/core/api/callback/BaseFlywayCallback.java
flyway-core/src/main/java/org/flywaydb/core/api/callback/FlywayCallback.java
flyway-core/src/main/java/org/flywaydb/core/api/migration/jdbc/BaseJdbcMigration.java
flyway-core/src/main/java/org/flywaydb/core/api/migration/jdbc/JdbcMigration.java
flyway-core/src/main/java/org/flywaydb/core/api/migration/spring/BaseSpringJdbcMigration.java
flyway-core/src/main/java/org/flywaydb/core/api/migration/spring/SpringJdbcMigration.java
flyway-core/src/main/java/org/flywaydb/core/api/resolver/BaseMigrationResolver.java
flyway-core/src/main/java/org/flywaydb/core/api/resolver/MigrationResolver.java

already implementing ConfigurationAware.
Changed javadoc to encourage usage of the abstract classes instead of implementing the interfaces directly.
Rationale: It makes sense to always implement ConfigurationAware, using a separate interface is basically to provide backward compatibility. Also, by using the abstract classes, we could transparently include new methods without breaking existing Migrations/Resolvers/Callbacks.

Included abstract base classes for resolvers and migrations 

---

flyway-core/src/main/resources/org/flywaydb/core/internal/dbsupport/redshift/upgradeMetaDataTable.sql

@axelfontaine 
I fixed the flyway 4 metadata upgrade for Redshift. Redshift does not support ALTER COLUMN, so we have to create new columns and copy the data instead.

Fixed flyway 4.0 upgrade for Redshift (it does not support alter column)

---

flyway-core/src/main/java/org/flywaydb/core/internal/dbsupport/postgresql/PostgreSQLSchema.java

This is a followup of previous PR for #1190. I don't know what happened but this change - described in https://github.com/flyway/flyway/pull/1157#issuecomment-174353875 - has been lost.
Tests runned and passed.

Postgres clean drop all types

---

flyway-core/src/main/java/org/flywaydb/core/Flyway.java
flyway-core/src/test/java/org/flywaydb/core/FlywaySmallTest.java

currently there's no way to actually set `placeholderReplacement` to false when invoking flyway via the commandline client, or at least I couldn't figure it out.
I think the documentation already includes this parameter in it.

Allow commandline client to specify placeholderReplacement

---

flyway-core/src/main/java/org/flywaydb/core/internal/info/MigrationInfoImpl.java
flyway-core/src/main/java/org/flywaydb/core/internal/resolver/ResolvedMigrationComparator.java
flyway-core/src/main/java/org/flywaydb/core/internal/util/ComparableUtils.java
flyway-core/src/test/java/org/flywaydb/core/internal/info/MigrationInfoServiceImplSmallTest.java
flyway-core/src/test/java/org/flywaydb/core/internal/util/ComparableUtilsTest.java

These changes should fix #1249 and #1274.
Migrations order is consistent now - first installed, then pending.

Fixed MigrationInfo.compareTo() implementation

---

flyway-core/src/main/resources/org/flywaydb/core/internal/dbsupport/oracle/upgradeMetaDataTable.sql

This change contains two modifications:
* delete the name of the PK to be dropped, because it is not valid SQL
(see https://docs.oracle.com/cd/E11882_01/server.112/e41084/statements_3001.htm#i2104014)
* implement the only working solution for #1235, which was initially suggested by @kevin-wimmer -
using the DROP INDEX clause

Proper fix for flyway 4.0 upgrade on Oracle [#1235]

---

flyway-core/src/main/resources/org/flywaydb/core/internal/dbsupport/mysql/createMetaDataTable.sql
flyway-core/src/main/resources/org/flywaydb/core/internal/dbsupport/mysql/upgradeMetaDataTable.sql

Currently, running MariaDB in a Galera cluster requires `innodb_force_primary_key=1` to be set. This breaks Flyway because it manipulates the primary key separately from defining the `schema_version` table.
The way to fix this for all of MySQL, MariaDB and MariaDB/Galera is to set the primary key in the `CREATE TABLE` statement, and if its being dropped and re-created on a different field then it can be done as part of the `ALTER` statement.
Fixes #1293

Allow Flyway to be used on MariaDB/Galera clusters

---

flyway-core/src/main/java/org/flywaydb/core/internal/util/scanner/classpath/ClassPathScanner.java

Migration during #979 fix introduced regression on #175
Migration to Location from String in ClassPathResolver on cbc9fef introduced regression in websphere hack from #175 in ClassPathScanner. Location there resolves to "classpath:db/migration/flyway.location" which renders resource not visible for IBM classloader. Added getPath() like in normal classloader flow. Tested on WebSphere 8.5.5.9 jdk8.

Fix IBM classloader regression

---

flyway-core/src/main/resources/org/flywaydb/core/internal/dbsupport/db2zos/upgradeMetaDataTable.sql

When dropping table in partitioned tablespace the drop fails with -669 in DB2. As the drop tablespace drops the table as well there is no need for this statement.

Removed drop table because of issues with partitioned tables

---

flyway-core/src/main/java/org/flywaydb/core/internal/dbsupport/sqlite/SQLiteSqlStatementBuilder.java
flyway-core/src/test/java/org/flywaydb/core/internal/dbsupport/sqlite/SQLiteSqlStatementBuilderSmallTest.java

`SQLiteSqlStatementBuilder` gets stuck in `insideQuoteStringLiteral` state when encounters [sqlite blob literals](https://www.sqlite.org/lang_expr.html) like `x'00'` or `X'00'`.

SQLite blob literal parsing support

---

flyway-core/src/main/java/org/flywaydb/core/internal/util/scanner/classpath/android/AndroidScanner.java

Local classLoader typed to ClassLoader, not PathClassLoader
Removed unnecessary cast causing error.

Fixed ClassCastException in AndroidScanner #1474

---

flyway-commandline/src/main/java/org/flywaydb/commandline/Main.java

Resolves https://github.com/flyway/flyway/issues/1382
According to the following [line](https://github.com/sw00/flyway/blob/0ef790a4a71e91297ce6ff02754dfa203be1fdfb/flyway-commandline/src/main/java/org/flywaydb/commandline/Main.java#L364), flyway will by default load `./flyway.conf` and not `conf/flyway.properties` when executed as a CLI.

Replace references to deprecated "flyway.properties" file.

---

flyway-core/src/main/java/org/flywaydb/core/internal/dbsupport/oracle/OracleSqlStatementBuilder.java

and relax the whitespace requirement when checking for delimiter change.

Add support for Oracle editionable objects

---

flyway-core/src/main/java/org/flywaydb/core/internal/command/DbBaseline.java
flyway-core/src/test/java/org/flywaydb/core/internal/command/DbBaselineTest.java

Baselining a second time after applying migrations threw an Exception even though the baseline version and description is the same. This PR allows executing the baseline command again after applying migrations **as long as the baseline version and description do not change**. In such a case the baseline command won't do anything.
This feature is especially useful in automated test environments where baselining or migrations might have taken place or not.
Before changing the `DbBasline` class, I wrote some unit tests to make sure that I don't accidentally break something. After changing the class I added some more tests for this new feature.

Make baseline() idempotent even after applying migrations

---

flyway-core/src/main/java/org/flywaydb/core/internal/resolver/CompositeMigrationResolver.java
flyway-core/src/main/java/org/flywaydb/core/internal/resolver/jdbc/JdbcMigrationResolver.java
flyway-core/src/main/java/org/flywaydb/core/internal/resolver/spring/SpringJdbcMigrationResolver.java
flyway-core/src/main/java/org/flywaydb/core/internal/resolver/sql/SqlMigrationResolver.java
flyway-core/src/test/java/org/flywaydb/core/internal/dbsupport/db2zos/DB2zOSMigrationMediumTest.java
flyway-core/src/test/java/org/flywaydb/core/internal/resolver/jdbc/JdbcMigrationResolverSmallTest.java
flyway-core/src/test/java/org/flywaydb/core/internal/resolver/spring/SpringJdbcMigrationResolverSmallTest.java
flyway-core/src/test/java/org/flywaydb/core/internal/resolver/sql/SqlMigrationResolverMediumTest.java
flyway-core/src/test/java/org/flywaydb/core/internal/resolver/sql/SqlMigrationResolverSmallTest.java
flyway-core/src/test/java/org/flywaydb/core/migration/MigrationTestCase.java

... instead of the previous 'one resolver per single location'. This makes the default resolvers behave more like custom resolvers and is a step on the way to eventually allow subclasses of default resolvers as custom resolvers.
This PR has no direct effect in itself, but provides only the base. 
This is basically a revisit of #1183 and #1185 
@axelfontaine : Since there will be more than one commit to this topic, I would rather put them all into one PR but as separate commits. Or do you rather want single PRs for all steps?

Make default resolvers handle all locations in one instance

---

flyway-core/src/main/java/org/flywaydb/core/internal/util/scanner/classpath/ClassPathScanner.java
flyway-core/src/main/java/org/flywaydb/core/internal/util/scanner/classpath/JarFileClassPathLocationScanner.java

Issue https://github.com/flyway/flyway/issues/1549
Untested proposed fix.
Patch against 4.1.2

Fix Tomcat URL handling fallout

---

flyway-core/src/main/java/org/flywaydb/core/api/callback/FlywayCallback.java

While reading the FlywayCallback docs faced that typo and changed it from **will** to **with**

Fix a minor typo in Javadoc

---

flyway-core/src/main/resources/org/flywaydb/core/internal/dbsupport/db2/upgradeMetaDataTable.sql

I believe this drop has to happen after the primary key change, so I put it at the end of the script.  This addresses issue #1586 
I don't see any tests to modify for this change.  I also don't have a build environment set up to test it, but it seems pretty cut and dried.

drop the _pk index to resolve issue with repeatable migrations

---

flyway-core/src/main/java/org/flywaydb/core/internal/dbsupport/postgresql/PostgreSQLSqlStatementBuilder.java

which must run outside of a transaction.
https://www.postgresql.org/docs/9.6/static/sql-dropindex.html

For Postgresql migrations, add support for "DROP INDEX CONCURRENTLY .*",

---

pom.xml

Since Java 8 is now the new minimum supported version for 5.0, now would be a good time to migrate MariaDB to 2.1.0.
https://mariadb.com/kb/en/mariadb/about-mariadb-connector-j/

Bump mariadb to 2.1.0

---

flyway-core/src/main/java/org/flywaydb/core/internal/dbsupport/db2/DB2Schema.java
flyway-core/src/test/java/org/flywaydb/core/internal/dbsupport/db2/DB2MigrationMediumTest.java
flyway-core/src/test/java/org/flywaydb/core/internal/util/scanner/classpath/ClassPathScannerSmallTest.java
flyway-core/src/test/resources/migration/dbsupport/db2/sql/procedure/V2__Procedure.sql

#1167 
P.S.: A little problem with build... I needed to comment the _scanForClassesSubPackage()_ of the **ClassPathScannerSmallTest** class to correctly create the build package. (the issue raised right after forking, so with no personal modification, I decided to do a pull request anyway)

pointing to specificname for procedures with same signature and support for cleaning temporary table too

---

flyway-core/src/main/java/org/flywaydb/core/internal/dbsupport/postgresql/PostgreSQLSchema.java
flyway-core/src/main/java/org/flywaydb/core/internal/dbsupport/postgresql/PostgreSQLTable.java

Speed up PostgreSQLTable.doExists()
Also speed up PostgreSQLSchema.doEmpty() - but this is not called as often as the 
former one
Issue:
https://github.com/flyway/flyway/issues/1701 - Table.exists() very slow in Postgres Environments with a lot of objects

PostgreSQL: Use system catalogs for Table.doExists() & Schema.doEmpty()

---

flyway-commandline/src/main/assembly/flyway.cmd

Added a check to see if CLASSPATH environment variable is set. If yes, then add the classpath variable to the java command classpath option

Use Windows CLASSPATH environment variable

---

flyway-commandline/src/main/assembly/flyway

This is a possible fix for #1642.
Cygwin detection fails on [Git for Windows](https://git-scm.com/) because `uname` returns `MSYS_NT-10.0` which does not match the known patterns. Instead of expanding the patterns, a more generic solution is to use `cygpath` if there is such a command.
I was not able to find any case in Google when `cygpath` was installed on a non-Windows system, therefore I think it is safe to assume that if `cygpath` is available, the classpath needs to be converted to a Windows path list. A better solution would be to let `cygpath` detect the system, but unfortunately this is not supported.
This pull request also replaces the `$(...)` syntax with backticks when calling `cygpath` to make the script more consistent. If this change poses an issue, please let me know and I …

Convert classpath with cygpath if it is available regardless of uname output

---

flyway-core/src/main/java/org/flywaydb/core/internal/util/jdbc/DriverDataSource.java

I would like to propose this change in order to support TestContainers JDBC connection string.
This way it will be possible to run database migration scripts against Dockerized database instance started by TestContainers.
Let me know if you have any questions.

Support TestContainers JDBC connection string

---

flyway-commandline/src/main/assembly/flyway.conf

Minor update to the example flyway.conf file bundled with the command line to explicitly show connections to oracle databases can be made using TNS names

Adding comment surrounding usage of Oracle TNS Connection string

---

flyway-gradle-plugin/src/main/java/org/flywaydb/gradle/task/AbstractFlywayTask.java

In Gradle 4.x, the method getClassesDir() in SourceSetOutput has been
deprecated in favor of a new method getClassesDirs().
Use reflection to invoke this method, if it is available, so that
consumers using Gradle 4.x are spared the deprecation warning. Fall back
to the original method for consumers using Gradle 3.x.
Fixes #1686

Tackle deprecation warning generated by Gradle 4.x

---

flyway-commandline/src/main/assembly/flyway.conf
flyway-commandline/src/main/java/org/flywaydb/commandline/Main.java
flyway-core/src/main/java/org/flywaydb/core/Flyway.java
flyway-core/src/main/java/org/flywaydb/core/api/configuration/FlywayConfiguration.java
flyway-core/src/main/java/org/flywaydb/core/internal/command/DbInfo.java
flyway-core/src/main/java/org/flywaydb/core/internal/command/DbMigrate.java
flyway-core/src/main/java/org/flywaydb/core/internal/command/DbRepair.java
flyway-core/src/main/java/org/flywaydb/core/internal/command/DbValidate.java
flyway-core/src/main/java/org/flywaydb/core/internal/configuration/ConfigUtils.java
flyway-core/src/main/java/org/flywaydb/core/internal/info/MigrationInfoContext.java
flyway-core/src/main/java/org/flywaydb/core/internal/info/MigrationInfoImpl.java
flyway-core/src/main/java/org/flywaydb/core/internal/info/MigrationInfoServiceImpl.java
flyway-gradle-plugin/src/main/java/org/flywaydb/gradle/FlywayExtension.java
flyway-gradle-plugin/src/main/java/org/flywaydb/gradle/task/AbstractFlywayTask.java
flyway-maven-plugin/src/main/java/org/flywaydb/maven/AbstractFlywayMojo.java

This is a pull request for issue #1865. 
The main change was done in MigrationInfoImpl class, where the new configuration flag is actually checked. All other changes are done taking as an example "flyway.ignoreMissingMigrations" configuration flag. I added a new option: "flyway.ignoreIgnoredMigrations". All changes in code take place next to a "missing" boolean flag.
I tried to follow all the conventions already applied in code. Also description of the configuration option in flyway.conf was done so that it is as similar to the description of surrounding "ignore..." flags, as possible.

New option to allow for 'Ignored' migrations in 'validate' command: ignoreIgnoredMigrations

---

flyway-core/src/main/java/org/flywaydb/core/internal/database/postgresql/PostgreSQLSchema.java

I cannot use `clean` in one of my projects, because I am using the btree_gist extension. I alway get the following error:
> ERROR: cannot drop type gbtreekey4 because extension btree_gist requires it
This PR prevents that these types are dropped. Basically this is an extension to commit 444f077116b45260d7f99aa931d41ccb59553c8a which did the same for routines and views.

Do not delete types that extensions depend on when cleaning PostgreSql

---

flyway-commandline/src/main/assembly/flyway.cmd

When calling flyway using System.Diagnostics.Process in .Net to create a database as part of my test suite setup I encountered a bug in Windows CMD with how %~dp0 is resolved, a bit of information and the solution I borrowed from can be found here: https://stackoverflow.com/a/26851883

Workaround a bug in windows cmd

---

pom.xml

Motivation:  Maven 'Zip Slip' vulnerability
https://maven.apache.org/security-plexus-archiver.html

upgrade Maven plugins

---

flyway-commandline/src/main/assembly/flyway.conf
flyway-commandline/src/main/java/org/flywaydb/commandline/Main.java
flyway-core/src/main/java/org/flywaydb/core/Flyway.java
flyway-core/src/main/java/org/flywaydb/core/api/configuration/ClassicConfiguration.java
flyway-core/src/main/java/org/flywaydb/core/api/configuration/Configuration.java
flyway-core/src/main/java/org/flywaydb/core/api/configuration/FluentConfiguration.java
flyway-core/src/main/java/org/flywaydb/core/internal/configuration/ConfigUtils.java
flyway-gradle-plugin/src/main/java/org/flywaydb/gradle/FlywayExtension.java
flyway-gradle-plugin/src/main/java/org/flywaydb/gradle/task/AbstractFlywayTask.java
flyway-maven-plugin/src/main/java/org/flywaydb/maven/AbstractFlywayMojo.java

This adds an 'ignorePendingMigrations' option to suppress validation errors caused by the availability of not-yet-applied migrations (feature request #2128).
My use case is for a CI/CD pipeline - while developers are working on a feature branch they should be able to create and modify migrations for that feature.  However, we should be able to detect and break the build when changes are made to versioned migrations that have already been applied to (e.g.) our production database.  Running `flyway validate` with `ignorePendingMigrations=true` supports this scenario and is consistent with the existing `ignore*Migrations` options.

Add an 'ignorePendingMigrations' configuration option

---

flyway-commandline/src/main/assembly/flyway.conf
flyway-core/src/main/java/org/flywaydb/core/api/configuration/ClassicConfiguration.java
flyway-core/src/main/java/org/flywaydb/core/api/configuration/Configuration.java
flyway-core/src/main/java/org/flywaydb/core/api/configuration/FluentConfiguration.java
flyway-maven-plugin/src/main/java/org/flywaydb/maven/AbstractFlywayMojo.java

While reading the documentation for `flyway migrate`, I noticed the explanation for `cleanOnValidationError` had a typo and changed it from `even tough` to `even though`.

Fix documentation typo

---

flyway-maven-plugin/src/main/java/org/flywaydb/maven/AbstractFlywayMojo.java

I am not able use multiple config files from pom.xml. After this commit is posible set multiple config files like:
```
<configFiles>
<configFile>flyway-dev.conf</configFile>
<configFile>flyway.conf</configFile>
</configFiles>
```

Enable configFiles configuration for maven plugin

---

flyway-core/src/main/java/org/flywaydb/core/api/MigrationType.java

Changed typo 'Bseline' to 'Baseline'

Fixed typo in MigrationType Javadoc

---

flyway-core/src/main/java/org/flywaydb/core/internal/logging/LogCreatorFactory.java

#2114
Using the context classloader in static context still doesn't allow for using slf4j or commons logging, but this way at least the fallback java util logging can be instantiated and start Flyway normally.

JavaUtilLog doesn't need to be instantiated with ClassUtils

---

flyway-gradle-plugin/src/main/java/org/flywaydb/gradle/task/AbstractFlywayTask.java

Hello,
thanks for great plugin :)
I have found a small issue in the Gradle Plugin:
When reading CONFIG_FILES from getProject().getProperties(), it was wrongly read from System.getProperties()
Greetings
Kevin

Gradle Plugin: Fix reading CONFIG_FILES from project properties

---

flyway-core/src/main/java/org/flywaydb/core/api/configuration/ClassicConfiguration.java
flyway-core/src/main/java/org/flywaydb/core/api/configuration/Configuration.java
flyway-core/src/main/java/org/flywaydb/core/api/configuration/FluentConfiguration.java
flyway-core/src/main/java/org/flywaydb/core/internal/database/oracle/OracleSchema.java
flyway-gradle-plugin/src/main/java/org/flywaydb/gradle/FlywayExtension.java
flyway-gradle-plugin/src/main/java/org/flywaydb/gradle/task/AbstractFlywayTask.java
flyway-maven-plugin/src/main/java/org/flywaydb/maven/AbstractFlywayMojo.java

Hi,
I just found a couple of duplicated words in the docs. Since this is my first PR on the project, please let me know if I can do something else when contributing such trivial fixes.
Cheers,
Christoph

Fix duplicate words in documentation

---

flyway-core/src/main/java/org/flywaydb/core/internal/database/oracle/OracleParser.java

When migration is:
`CREATE OR REPLACE PACKAGE test AS
LS_TEST_IDENTIFIERS VARCHAR2(1 CHAR) := 'R';
FUNCTION FT( AS_IDENTIFIER VARCHAR2 ) RETURN VARCHAR2;
END TEST;
/
CREATE OR REPLACE PACKAGE BODY TEST AS
FUNCTION FT (AS_IDENTIFIER VARCHAR2) RETURN VARCHAR2 IS
BEGIN
CASE LS_TEST_IDENTIFIERS
WHEN  'R' THEN
RETURN AS_IDENTIFIER;
END CASE ;
END FT;
END TEST;
/
`
and method adjustBlockDepth is:
`    @Override
protected void adjustBlockDepth(ParserContext context, List<Token> tokens, Token keyword) {
String keywordText = keyword.getText();
int parensDepth = keyword.getParensDepth();
if ("BEGIN".equals(keywordText) || "CASE".equals(keywordText)
|| (("IF".equals(keywordText) || "LOOP".equals(keywordText)) && !containsWithinLast(1, tokens, parensDepth, "END"))
|| ("TRIGGER".equals(keywordText) && …

Not worked migration when plsql contains CASE statement

---

flyway-core/src/main/java/org/flywaydb/core/internal/configuration/ConfigUtils.java

There is currently no way to define the default schema through environment variables.

Add environment variable for defaultSchema

---

flyway-commandline/src/main/assembly/flyway.conf

Addresses a recent open issue (and two other closed ones). One simple line.

Allow setting flyway.url=<valid-url> at the top of flyway.conf.

---

flyway-core/src/main/java/org/flywaydb/core/internal/database/mysql/MySQLSchema.java

Associated issue: #2123
This fix improves the performance of `MySQLSchema.doEmpty` for MySQL 5.7 without changing the expected behavior.
The subquery `SELECT 1 as found FROM information_schema.triggers WHERE trigger_schema=? AND  LIMIT 1` is changed to `SELECT 1 as found FROM information_schema.triggers WHERE event_object_schema=? AND  LIMIT 1` (`WHERE trigger_schema=?` becomes `WHERE event_object_schema=?`).
As specified here: https://dev.mysql.com/doc/mysql-infoschema-excerpt/5.7/en/triggers-table.html, "every trigger is associated with exactly one table" and `EVENT_OBJECT_SCHEMA` is the "schema (database) in which this table occurs" and `TRIGGER_SCHEMA` is the "name of the schema (database) to which the trigger belongs". If a trigger belongs to a table that belongs to schema X, then …

Fix slow doEmpty by using EVENT_OBJECT_SCHEMA (#2123)

---

flyway-core/src/main/java/org/flywaydb/core/internal/database/postgresql/PostgreSQLParser.java
flyway-core/src/main/java/org/flywaydb/core/internal/database/snowflake/SnowflakeParser.java

Multiple $$...$$ literals were causing the Snowflake parser not to identify statements correctly

Fix #2843 Multiple $$ string literals 

---

flyway-core/src/main/java/org/flywaydb/core/internal/scanner/Scanner.java

Hey, realize this isn't fully inline with the contributing guidelines, but the fix is pretty small so I opened a PR without an issue. If that's an issue (haha) I can re-open this.
I noticed with 6.5.3 that an application I have that has a few hundred migrations now takes ~30 seconds (used to be ~2 seconds on 6.5.2) to run in my CI environment (it's an old amazon linux ami, if it matters). Locally (on OSX), performance seems a little worse (~5 seconds -> ~8 seconds). It seems like it's because of commit https://github.com/flyway/flyway/commit/ecfebd2e99f9ac507c3af3627dad6d149dc89335. 
This PR inlines the `getAbsolutePathOnDisk` call to the right side of the `or` statement so it can be skipped when the cheap `getRelativePath` equality check is true.

Perform disk operation in right side of or statement

---

pom.xml

Versions of the postgres jdbc driver prior to 42.2.13 have an XXE vulnerability, according to this: https://nvd.nist.gov/vuln/detail/CVE-2020-13692
Would it be possible to bump the version to 42.2.13 to address this?

Updating postgres version because of XXE vulnerability

---

documentation/Flyway CLI and API/Supported Databases/TestContainers.md
documentation/Flyway CLI and API/Welcome To Flyway.md
documentation/Release notes and older versions/Release Notes for Flyway Engine.html

The name of the project is Testcontainers.
See https://testcontainers.com/

Fix Testcontainers project name

---

documentation/Flyway CLI and API/Configuration/Parameters/Baseline Migration Prefix.md
documentation/Flyway CLI and API/Configuration/Parameters/Dapr Secrets.md
documentation/Flyway CLI and API/Configuration/Parameters/Dapr URL.md
documentation/Flyway CLI and API/Configuration/Parameters/Google Cloud Secret Manager Project.md
documentation/Flyway CLI and API/Configuration/Parameters/Google Cloud Secret Manager Secrets.md
documentation/Flyway CLI and API/Configuration/Parameters/PostgreSQL Transactional Lock.md
documentation/Flyway CLI and API/Configuration/Parameters/SQL Server Kerberos Login File.md
documentation/Flyway CLI and API/Configuration/Parameters/Vault Secrets.md
documentation/Flyway CLI and API/Configuration/Parameters/Vault Token.md
documentation/Flyway CLI and API/Configuration/Parameters/Vault URL.md

I encountered errors using the `postgresqlTransactionalLock` example using Gradle 6.8.3 and 7.4, so this corrects the syntax for all similar examples that I could find.
In "documentation/Flyway CLI and API/Configuration/Parameters/PostgreSQL Transactional Lock.md", without the change to line 42, Gradle is unable to compile the build script, reporting:
> You tried to use a map entry for an index operation, this is not allowed. Maybe something should be set in parentheses or a comma is missing?
Without the change to line 43, the `flywayMigrate` task fails with:
> class java.lang.Boolean cannot be cast to class java.lang.String (java.lang.Boolean and java.lang.String are in module java.base of loader 'bootstrap')

fix Gradle plugin configuration syntax in documentation
